# -*- coding: utf-8 -*-
"""03a_CV_yolo11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/114fr84d4TjoaV6y0tYbgeKczJ09QlCnJ
"""

!pip install ultralytics

import os
import shutil
import torch
from ultralytics import YOLO

from google.colab import drive
drive.mount('/content/drive')

import os
os.makedirs("models/yolo11", exist_ok=True)

!ls models/yolo11

data_yaml_path = "data/processed/object_detection/yolo11/data.yaml"

device = "cuda" if torch.cuda.is_available() else "cpu"
device

model = YOLO("yolo11n.yaml")

train_results = model.train(
    data=data_yaml_path,
    epochs=100,
    imgsz=640,
    batch=8,
    optimizer="Adam",
    device=0,
    workers=2,
    patience=20000,
    save_period=20,
    plots=True,
    project="outputs/training/yolo11"
)

import shutil

src = "outputs/training/yolo11/train/weights/best.pt"
dst = "models/yolo11/best.pt"
shutil.copy(src, dst)

print("Modello salvato su Drive!")

val = model.val()
print(" METRICHE VALIDATION")
print(f"Precision        : {val.results_dict['metrics/precision(B)']:.3f}")
print(f"Recall           : {val.results_dict['metrics/recall(B)']:.3f}")
print(f"mAP50            : {val.results_dict['metrics/mAP50(B)']:.3f}")
print(f"mAP50-95         : {val.results_dict['metrics/mAP50-95(B)']:.3f}")
